[package]
name = "pascal-like"
version = "0.1.0"
authors = ["statiolake <statiolake@gmail.com>"]
edition = "2018"

[dependencies]
dyn-clone = "1.0.4"
glob = "0.3.0"
itertools = "0.10.0"
maplit = "1.0.2"
once_cell = "1.7.2"
rand = "0.8.3"
termcolor = "1.1.2"
thiserror = "1.0.25"
